version: '3'

services:
    db:
        image: postgres
        restart: always
        volumes:
            - ./sql:/var/lib/postgresql
        environment:
            POSTGRES_DATABASES: gomitas
            POSTGRES_ROOT_PASSWORD: 1234
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 1234
            POSTGRES_MY_DATABASE: gomitas
            POSTGRES_ROOT_HOST: '%'
        ports:
            - 5432:5432
            
    app:
        image: maven
        restart: always
        working_dir: /Gomitas
        volumes:
            - ./Gomitas:/Gomitas
        ports:
            - 8081:8081
        command: ls -a
        links:
            - db