version: '3'

volumes:
sql: {}

services:
    db:
        image: mysql
        #restart: always
        environment:
            MYSQL_DATABASES: gomitasDB
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: mysql
            MYSQL_MY_DATABASE: gomitasDB
            MYSQL_ROOT_HOST: '%'
        ports:
            - 3306:3306
        volumes:
            - ./sql:/var/lib/mysql
            - ./gomitas-schema.sql/:/docker-entrypoint-initdb.d/gomitas-schema.sql
            
    app:
        image: maven
        #restart: always
        working_dir: /Gomitas
        volumes:
            - ./Gomitas:/Gomitas
        ports:
            - 8081:8081
        command: mvn spring-boot:run
        links:
            - db