version: '3'

services:
    db:
        image: mysql
        #restart: always
        volumes:
            - ./sql:/var/lib/mysql
            #- ./sql/data:/var/lib/mysql/data
        environment:
            MYSQL_DATABASES: gomitasDB
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: mysql
            MYSQL_MY_DATABASE: gomitasDB
            MYSQL_ROOT_HOST: '%'
        ports:
            - 3306:3306
            
    app:
        image: maven
        #restart: always
        working_dir: /Gomitas
        volumes:
            - ./Gomitas:/Gomitas
        ports:
            - 8081:8081
        command: mvn spring-boot:run
        links:
            - db