version: '3'

services:
    db:
        image: mysql
        restart: always
        volumes:
            - ./sql:/var/lib/mysql
            #- ./sql/data:/var/lib/mysql/data
        environment:
            POSTGRES_DATABASES: gomitasDB
            POSTGRES_ROOT_PASSWORD: mysql
            POSTGRES_USER: root
            POSTGRES_PASSWORD: mysql
            POSTGRES_MY_DATABASE: gomitasDB
            POSTGRES_ROOT_HOST: '%'
        ports:
            - 3306:3306
            
    app:
        image: maven
        restart: always
        working_dir: /Gomitas
        volumes:
            - ./Gomitas:/Gomitas
        ports:
            - 8081:8081
        command: mvn spring-boot:run
        links:
            - db