version: '3'

services:
    db:
        image: postgres
        restart: always
        volumes:
            - ./sql:/var/lib/postgresql
        environment:
            POSTGRES_PASSWORD: 1234
        ports:
            - 5432:5432
            
    app:
        image: maven
        restart: always
        working_dir: /Gomitas
        volumes:
            - ./Gomitas:/Gomitas
        ports:
            - 8081:8081
        command: ls -a
        #links:
        #    - db